---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: devops-toolkit
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/Tycho-1/devops-toolkit
